on: workflow_dispatch

name: PBP Rebuild

jobs:
  update:
    name: PBP Rebuild
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install pak and nflfastR
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          pak::pkg_system_requirements("nflfastR", sudo = TRUE, execute = TRUE)
          pak::pak(c("nflverse/nflfastR"), dependencies = TRUE)
          pak::pak(c("readr","arrow","callr"))
        shell: Rscript {0}
      - name: Run update script
        run: Rscript -e 'source("R/update_all_seasons_pbp.R")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          Rscript -e 'source("R/make_pbp_commit.R")'
          git push origin master || echo "No changes to commit"
