on:
  schedule:
    # runs every day at 9:00 AM UTC in jan, feb, sep-dec
    - cron:  '0 9 * 1,2,9-12 *'
  workflow_dispatch:

name: update_current_season_pbp_and_stats

jobs:
  update:
    name: update_pbp
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1

      - name: Install dependencies from DESCRIPTION
        uses: r-lib/actions/setup-r-dependencies@v1
        with:
           cache-version: 1
           extra-packages: |
            nflverse/nflfastR
            nflverse/nflreadr

      - name: Run pbp update
        run: Rscript -e 'source("R/update_current_season_pbp.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'writeLines(paste0("export NFLFASTR_VERSION=",as.character(packageVersion("nflfastR"))),".ver")'
          source .ver
          git pull
          git add data
          git commit -m "Updated on `date` using nflfastR version $NFLFASTR_VERSION"  || echo "No changes to commit"
          git push origin master || echo "No changes to commit"

      - name: Run player_stats script
        run: Rscript -e 'source("R/save_stats.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'writeLines(paste0("export NFLFASTR_VERSION=",as.character(packageVersion("nflfastR"))),".ver")'
          source .ver
          git pull
          git add data
          git commit -m "Updated on `date` using nflfastR version $NFLFASTR_VERSION"  || echo "No changes to commit"
          git push origin master || echo "No changes to commit"
